MvcCoreLinqToSQL/Models/Empleado.cs
namespace MvcCoreLinqToSQL.Models
{
    public class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Apellido { get; set; }
        public string Oficio { get; set; }
        public int Salario { get; set; }
        public int IdDepartamento { get; set; }
    }
}

MvcCoreLinqToSQL/Models/ErrorViewModel.cs
namespace MvcCoreLinqToSQL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreLinqToSQL/Models/ResumenEmpleados.cs
namespace MvcCoreLinqToSQL.Models
{
    public class ResumenEmpleados
    {
        public int Personas { get; set; }
        public int MaximoSalario { get; set; }
        public double MediaSalarial { get; set; }
        public List<Empleado> Empleados { get; set; }
    }
}

MvcCoreLinqToSQL/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToSQL.Models;
using MvcCoreLinqToSQL.Repositories;

namespace MvcCoreLinqToSQL.Controllers
{
    public class EmpleadosController : Controller
    {
        RepositoryEmpleados repo;
        public EmpleadosController()
        {
            this.repo = new RepositoryEmpleados();
        }
        public IActionResult Index()
        {
            List<Empleado> empleados = this.repo.GetEmpleados();
            return View(empleados);
        }

        public IActionResult Details(int idEmpleado)
        {
            Empleado empleado = this.repo.FindEmpleado(idEmpleado);
            return View(empleado);
        }
        public IActionResult BuscadorEmpleados()
        {
            return View();
        }

        [HttpPost]
        public IActionResult BuscadorEmpleados(string oficio, int salario)
        {
            List<Empleado> empleados = 
                this.repo.GetEmpleadosOficioSalario(oficio, salario);
            if (empleados == null)
            {
                ViewData["MENSAJE"] = "No existen empleados con oficio " +
                    oficio + " y salario superior a " + salario;
                return View();
            } else
            {
                return View(empleados);
            }
        }

        public IActionResult EmpleadosOficio()
        {
            ViewData["OFICIOS"] = this.repo.GetOficios();
            return View();
        }

        [HttpPost]
        public IActionResult EmpleadosOficio(string oficio)
        {
            ResumenEmpleados resumen = this.repo.GetEmpleadosOficio(oficio);
            ViewData["OFICIOS"] = this.repo.GetOficios();
            return View(resumen);
        }
    }
}

MvcCoreLinqToSQL/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToSQL.Models;

namespace MvcCoreLinqToSQL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreLinqToSQL/Views/Empleados/BuscadorEmpleados.cshtml
<h1> Buscador Linq To SQL</h1>

<form method="post">
	<label class="form-label">Oficio: </label>
	<input type="text" class="form-control" name="oficio" />
	<label class="form-label">Salario: </label>
	<input type="text" class="form-control" name="salario" />
	<button class="btn btn-dark my-3">
		Buscar
	</button>
</form>

<h2 style="color: red">
	@ViewData["MENSAJE"]
</h2>

@if (Model != null) {
	<table class="table table-light table-striped">
		<thead>
			<tr>
				<th>
					Apellido
				</th>
				<th>
					Oficio
				</th>
				<th>
					Salario
				</th>
			</tr>
		</thead>
		<tbody>
			@foreach (Empleado emp in Model)
			{
				<tr>
					<td>@emp.Apellido</td>
					<td>@emp.Oficio</td>
					<td>@emp.Salario</td>
				</tr>
			}
		</tbody>
	</table>
}

MvcCoreLinqToSQL/Views/Empleados/Details.cshtml
@model Empleado

<a asp-action="Index"
asp-controller="Empleados">
	Back To List
</a>

<ul class="list-group">
	<li class="list-group-item">
		@Model.IdEmpleado
	</li>
	<li class="list-group-item">
		@Model.Apellido
	</li>
	<li class="list-group-item">
		@Model.Oficio
	</li>
	<li class="list-group-item">
		@Model.Salario
	</li>
	<li class="list-group-item">
		@Model.IdDepartamento
	</li>
</ul>

MvcCoreLinqToSQL/Views/Empleados/EmpleadosOficio.cshtml
@model ResumenEmpleados

@{
    List<string> oficios = 
        ViewData["OFICIOS"] as List<string>;
}

<h1>Empleados Oficio</h1>

<form method="post">
	<label class="form-label">Introduzca un oficio: </label>
    <select class="form-select" name="oficio">
        @foreach(string oficio in oficios) {
            <option value="@oficio">@oficio</option>
        }
    </select>
	<button class="btn btn-dark my-3">
		Filtrar Empleados
	</button>
</form>

@if (Model != null)
{
    <ul class="list-group">
        <li class="list-group-item active">
            Personas: @Model.Personas
        </li>
        <li class="list-group-item">
            Maximo Salario: @Model.MaximoSalario
        </li>
        <li class="list-group-item">
            Media Salarial: @Model.MediaSalarial
        </li>
    </ul>

    <h2 class="font-monospace mt-2">Visualizar Empleados</h2>

    <table class="table table-hover mb-0">
        <thead class="table-light">
            <tr>
                <th scope="col">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value=""
                               id="select_all" />
                    </div>
                </th>
                <th scope="col">Apellido</th>
                <th scope="col">Oficio</th>
                <th scope="col">Salario</th>
                <th scope="col">ACTION</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Empleado empleado in Model.Empleados)
            {
                <tr>
                    <th scope="row">
                        <div class="form-check">
                            <input class="form-check-input checkbox" type="checkbox" value=""
                                   id="flexCheckDefault1" checked />
                        </div>
                    </th>
                    <td>@empleado.Apellido</td>
                    <td>@empleado.Oficio</td>
                    <td>@empleado.Salario</td>
                    <td>
                        <button type="button" class="btn btn-success btn-sm px-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
                            </svg>
                        </button>
                        <button type="button" class="btn btn-warning btn-sm px-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z" />
                                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0" />
                            </svg>
                        </button>
                        <button type="button" class="btn btn-danger btn-sm px-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z" />
                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z" />
                            </svg>
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

MvcCoreLinqToSQL/Views/Empleados/Index.cshtml
@model List<Empleado>

	<h1> Empleados Linq To SQL</h1>

	<table class="table table-light table-striped">
		<thead>
			<tr>
				<th>
					Emp_no
				</th>
				<th>
					Apellido
				</th>
				<th>
					Oficio
				</th>
				<th>
					Detalles
				</th>
			</tr>
		</thead>
		<tbody>
			@foreach(Empleado emp in Model) {
				<tr>
					<td>@emp.IdEmpleado</td>
					<td>@emp.Apellido</td>
					<td>@emp.Oficio</td>
					<td>
						<a asp-action="Details"
						asp-controller="Empleados"
						asp-route-idEmpleado="@emp.IdEmpleado">
							Details
						</a>
					</td>
				</tr>
			}
		</tbody>
	</table>

MvcCoreLinqToSQL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreLinqToSQL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreLinqToSQL</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreLinqToSQL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreLinqToSQL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                            asp-controller="Empleados" 
                            asp-action="Index">
                                Empleados
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Empleados"
                               asp-action="BuscadorEmpleados">
                                Buscador
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Empleados"
                               asp-action="EmpleadosOficio">
                                ResumenEmpleados
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MvcCoreLinqToSQL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>